/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import alta.AltaColeccion;
import alta.AltaComic;
import baja.BajaColeccion;
import baja.BajaComic;
import java.net.URL;
import javax.help.HelpBroker;
import javax.help.HelpSet;
import javax.help.HelpSetException;
import modificacion.ModificacionColeccion;
import modificacion.ModificacionComic;
import ventanaInformes.InformesColecciones;
import ventanaInformes.InformesComics;

/**
 *
 * @author Dani
 */
public class PantallaGestion extends javax.swing.JFrame {
    private HelpBroker helpBroker;
    private HelpSet helpSet;
    /**
     * Creates new form PantallaGestion
     */
    public PantallaGestion() {
        initComponents();
        URL url = null;
        // abre ayuda
        try {
            System.out.println("Cargando ayuda");
            url = this.getClass().getResource("/ayudas/ayuda.hs");
            helpSet = new HelpSet(null, url);
            helpBroker = helpSet.createHelpBroker();
            helpBroker.enableHelpOnButton(miAyudaContenido, "index", helpSet);
        } catch (HelpSetException ex) {
            System.out.println("Error cargando la ayuda!!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        mGestion = new javax.swing.JMenu();
        mComics = new javax.swing.JMenu();
        miComicAlta = new javax.swing.JMenuItem();
        miComicBaja = new javax.swing.JMenuItem();
        miComicModificacion = new javax.swing.JMenuItem();
        mColecciones = new javax.swing.JMenu();
        miColeccionAlta = new javax.swing.JMenuItem();
        miColeccionBaja = new javax.swing.JMenuItem();
        miColeccionModificacion = new javax.swing.JMenuItem();
        miSalir = new javax.swing.JMenuItem();
        mAyuda = new javax.swing.JMenu();
        miAyudaContenido = new javax.swing.JMenuItem();
        mInformes = new javax.swing.JMenu();
        miInformesComic = new javax.swing.JMenuItem();
        miInformesColeccion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión");
        setExtendedState(6);

        mGestion.setMnemonic('f');
        mGestion.setText("Gestion");

        mComics.setText("Comics");

        miComicAlta.setText("Alta");
        miComicAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miComicAltaActionPerformed(evt);
            }
        });
        mComics.add(miComicAlta);

        miComicBaja.setText("Baja");
        miComicBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miComicBajaActionPerformed(evt);
            }
        });
        mComics.add(miComicBaja);

        miComicModificacion.setText("Modificación");
        miComicModificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miComicModificacionActionPerformed(evt);
            }
        });
        mComics.add(miComicModificacion);

        mGestion.add(mComics);

        mColecciones.setText("Colecciones");

        miColeccionAlta.setText("Alta");
        miColeccionAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miColeccionAltaActionPerformed(evt);
            }
        });
        mColecciones.add(miColeccionAlta);

        miColeccionBaja.setText("Baja");
        miColeccionBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miColeccionBajaActionPerformed(evt);
            }
        });
        mColecciones.add(miColeccionBaja);

        miColeccionModificacion.setText("Modificacion");
        miColeccionModificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miColeccionModificacionActionPerformed(evt);
            }
        });
        mColecciones.add(miColeccionModificacion);

        mGestion.add(mColecciones);

        miSalir.setMnemonic('x');
        miSalir.setText("Salir");
        miSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSalirActionPerformed(evt);
            }
        });
        mGestion.add(miSalir);

        menuBar.add(mGestion);

        mAyuda.setMnemonic('h');
        mAyuda.setText("Ayuda");

        miAyudaContenido.setMnemonic('c');
        miAyudaContenido.setText("Contenido");
        miAyudaContenido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAyudaContenidoActionPerformed(evt);
            }
        });
        mAyuda.add(miAyudaContenido);

        menuBar.add(mAyuda);

        mInformes.setText("Informes");

        miInformesComic.setText("Comics");
        miInformesComic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miInformesComicActionPerformed(evt);
            }
        });
        mInformes.add(miInformesComic);

        miInformesColeccion.setText("Colecciones");
        miInformesColeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miInformesColeccionActionPerformed(evt);
            }
        });
        mInformes.add(miInformesColeccion);

        menuBar.add(mInformes);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 823, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(839, 749));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void miSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_miSalirActionPerformed

    private void miComicAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miComicAltaActionPerformed
        // abre ventana alta comic
        AltaComic altaComic = new AltaComic();
        desktopPane.add(altaComic);
        altaComic.setVisible(true);
    }//GEN-LAST:event_miComicAltaActionPerformed

    private void miComicBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miComicBajaActionPerformed
        // abre ventana baja comic
        BajaComic bajaComic = new BajaComic();
        desktopPane.add(bajaComic);
        bajaComic.setVisible(true);
    }//GEN-LAST:event_miComicBajaActionPerformed

    private void miComicModificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miComicModificacionActionPerformed
        // abre ventana modificacion comic
        ModificacionComic modificacionComic = new ModificacionComic();
        desktopPane.add(modificacionComic);
        modificacionComic.setVisible(true);
    }//GEN-LAST:event_miComicModificacionActionPerformed

    private void miColeccionAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miColeccionAltaActionPerformed
        // abre ventana alta coleccion
        AltaColeccion altaColeccion = new AltaColeccion();
        desktopPane.add(altaColeccion);
        altaColeccion.setVisible(true);
    }//GEN-LAST:event_miColeccionAltaActionPerformed

    private void miColeccionBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miColeccionBajaActionPerformed
        // abre ventana baja coleccion
        BajaColeccion bajaColeccion = new BajaColeccion();
        desktopPane.add(bajaColeccion);
        bajaColeccion.setVisible(true);
    }//GEN-LAST:event_miColeccionBajaActionPerformed

    private void miColeccionModificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miColeccionModificacionActionPerformed
        // abre modificacion coleccion
        ModificacionColeccion modificacionColeccion = new ModificacionColeccion();
        desktopPane.add(modificacionColeccion);
        modificacionColeccion.setVisible(true);
    }//GEN-LAST:event_miColeccionModificacionActionPerformed

    private void miInformesComicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miInformesComicActionPerformed
        // abre informe comics
        InformesComics informeComics = new InformesComics();
        desktopPane.add(informeComics);
        informeComics.setVisible(true);
    }//GEN-LAST:event_miInformesComicActionPerformed

    private void miInformesColeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miInformesColeccionActionPerformed
        // abre informesColecciones
        InformesColecciones informesColecciones = new InformesColecciones();
        desktopPane.add(informesColecciones);
        informesColecciones.setVisible(true);
    }//GEN-LAST:event_miInformesColeccionActionPerformed

    private void miAyudaContenidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAyudaContenidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miAyudaContenidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaGestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaGestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaGestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaGestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaGestion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu mAyuda;
    private javax.swing.JMenu mColecciones;
    private javax.swing.JMenu mComics;
    private javax.swing.JMenu mGestion;
    private javax.swing.JMenu mInformes;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem miAyudaContenido;
    private javax.swing.JMenuItem miColeccionAlta;
    private javax.swing.JMenuItem miColeccionBaja;
    private javax.swing.JMenuItem miColeccionModificacion;
    private javax.swing.JMenuItem miComicAlta;
    private javax.swing.JMenuItem miComicBaja;
    private javax.swing.JMenuItem miComicModificacion;
    private javax.swing.JMenuItem miInformesColeccion;
    private javax.swing.JMenuItem miInformesComic;
    private javax.swing.JMenuItem miSalir;
    // End of variables declaration//GEN-END:variables

}
