/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanaInformes;

import clases.Comic;
import clases.Conexion;
import configuracion.ConfiguracionesBD;
import java.awt.Image;
import java.io.IOException;
import java.io.InputStream;
import java.net.URISyntaxException;
import java.net.URL;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Dani
 */
public class InformesComics extends javax.swing.JInternalFrame {

    /**
     * Creates new form InformesComics
     */
    public InformesComics() {
        initComponents();
        cmbComics.setModel(modeloComics);
        rellenarComics();
        
    }
/**
     * rellena el combobox de comics
     */
    public static void rellenarComics(){
        modeloComics.removeAllElements();
        try {
            Statement stm = Conexion.getConexion().createStatement();
            ResultSet rs = stm.executeQuery("select id, titulo, fecha_adquisicion,"
                    + "numero_coleccion, precio, portada, estado, id_coleccion "
                    + "from comics order by titulo");
            while(rs.next()){
                Comic comic = new Comic(rs.getInt(1), rs.getString(2),
                new Date(rs.getDate(3).getTime()), rs.getInt(4), rs.getFloat(5), rs.getBlob(6),
                        rs.getString(7), rs.getInt(8));
                modeloComics.addElement(comic);
            }
        } catch (SQLException e) {
            System.out.println(""+e.getErrorCode());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btnInformePredefinido = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cmbComics = new javax.swing.JComboBox<>();
        btnInformePersonalizado = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Informes Comics");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        btnInformePredefinido.setText("Generar informe predefinido");
        btnInformePredefinido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformePredefinidoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(btnInformePredefinido, gridBagConstraints);

        jLabel1.setText("Comic");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(jLabel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(cmbComics, gridBagConstraints);

        btnInformePersonalizado.setText("Generar informe personalizado");
        btnInformePersonalizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformePersonalizadoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(btnInformePersonalizado, gridBagConstraints);

        setBounds(0, 0, 512, 187);
    }// </editor-fold>//GEN-END:initComponents

    private void btnInformePredefinidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformePredefinidoActionPerformed
        URL url = null;        
        HashMap datos = new HashMap();
        // genera informe de clientes de BD
        if(!ConfiguracionesBD.SISTEMA_EN_PRODUCCION){
            System.out.println("Desarrollo");
            url = this.getClass().getResource("/informes");
            String directorioInformes = "";
            try {
                directorioInformes = url.toURI().getPath();
                String informe = directorioInformes.concat("/informeComics.jrxml");
                JasperReport jasperReport = JasperCompileManager.compileReport(informe);
                JasperPrint impresion = JasperFillManager.fillReport(jasperReport, datos, Conexion.getConexion());
                if(impresion.getPages().isEmpty()){
                    JOptionPane.showMessageDialog(this, "No hay datos que mostrar");
                    return;
                }
                JasperViewer.viewReport(impresion, false);
            } catch (URISyntaxException ex) {
                System.out.println("Error de uri en informe comics!!");
            } catch (JRException ex) {
                System.out.println("Error llenando el informe comics!!");
            } 
        }else{
            System.out.println("Producción");
            try {
                InputStream informe = this.getClass().getResourceAsStream
                ("/informes/informeComics.jrxml");
                JasperReport jasperReport = JasperCompileManager.compileReport(informe);
                JasperPrint impresion = JasperFillManager.fillReport(jasperReport, null, Conexion.getConexion());
                if(impresion.getPages().isEmpty()){
                    JOptionPane.showMessageDialog(this, "No hay datos que mostrar");
                    return;
                }
                JasperViewer.viewReport(impresion, false);
            } catch (JRException ex) {
                Logger.getLogger(InformesComics.class.getName()).log(Level.SEVERE, null, ex);
            } 
            
        }
    }//GEN-LAST:event_btnInformePredefinidoActionPerformed

    private void btnInformePersonalizadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformePersonalizadoActionPerformed
        if(cmbComics.getSelectedIndex() == -1){
            JOptionPane.showMessageDialog(this, "Selecciona un comic");
            return;
        }
        URL url = null;  
        Comic comic = (Comic) cmbComics.getSelectedItem();
        HashMap datos = new HashMap();
        // genera informe de clientes de BD
        if(!ConfiguracionesBD.SISTEMA_EN_PRODUCCION){
            System.out.println("Desarrollo");
            url = this.getClass().getResource("/informes");
            String directorioInformes = "";
            try {
                directorioInformes = url.toURI().getPath();
                String informe = directorioInformes.concat("/informePersonalizadoComics.jrxml");
                JasperReport jasperReport = JasperCompileManager.compileReport(informe);
                //se le pasa el parametro idComic
                datos.put("IdComic", comic.getId());
                JasperPrint impresion = JasperFillManager.fillReport(jasperReport, datos, Conexion.getConexion());
                if(impresion.getPages().isEmpty()){
                    JOptionPane.showMessageDialog(this, "No hay datos que mostrar");
                    return;
                }
                JasperViewer.viewReport(impresion, false);
            } catch (URISyntaxException ex) {
                System.out.println("Error de uri en informe comics!!");
            } catch (JRException ex) {
                System.out.println("Error llenando el informe comics!!");
            } 
        }else{
            System.out.println("Producción");
            try {
                InputStream informe = this.getClass().getResourceAsStream
                ("/informes/informePersonalizadoComics.jrxml");
                datos.put("IdComic", comic.getId());
                JasperReport jasperReport = JasperCompileManager.compileReport(informe);
                JasperPrint impresion = JasperFillManager.fillReport(jasperReport, datos, Conexion.getConexion());
                if(impresion.getPages().isEmpty()){
                    JOptionPane.showMessageDialog(this, "No hay datos que mostrar");
                    return;
                }
                JasperViewer.viewReport(impresion, false);
            } catch (JRException ex) {
                Logger.getLogger(InformesComics.class.getName()).log(Level.SEVERE, null, ex);
            } 
            
        }
    }//GEN-LAST:event_btnInformePersonalizadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInformePersonalizado;
    private javax.swing.JButton btnInformePredefinido;
    private javax.swing.JComboBox<Comic> cmbComics;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    private static DefaultComboBoxModel<Comic> modeloComics = new DefaultComboBoxModel<>();
}
