/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package alta;

import baja.BajaColeccion;
import baja.BajaComic;
import clases.Conexion;
import clases.DocumentoLongitudRestringida;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.event.InternalFrameEvent;
import javax.swing.event.InternalFrameListener;
import modificacion.ModificacionColeccion;
import modificacion.ModificacionComic;
import ventanaInformes.InformesColecciones;
import ventanaInformes.InformesComics;

/**
 *
 * @author Dani
 */
public class AltaColeccion extends javax.swing.JInternalFrame {

    /**
     * Creates new form AltaColeccion
     */
    public AltaColeccion() {
        initComponents();
        txtNombre.setDocument(new DocumentoLongitudRestringida(50));
        txtaSinopsis.setDocument(new DocumentoLongitudRestringida(100));
    }
    /**
     * limpia los campos del formulario
     */
    private void limpiar(){
        txtNombre.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        txtaSinopsis = new javax.swing.JTextArea();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Alta Coleccion");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Nombre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(jLabel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(txtNombre, gridBagConstraints);

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(btnAceptar, gridBagConstraints);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(btnCancelar, gridBagConstraints);

        jLabel2.setText("Sinopsis");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(jLabel2, gridBagConstraints);

        txtaSinopsis.setColumns(20);
        txtaSinopsis.setRows(5);
        jScrollPane.setViewportView(txtaSinopsis);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(jScrollPane, gridBagConstraints);

        setBounds(0, 0, 518, 297);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // cierra la ventana
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        
        ///validación
        if(txtNombre.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Falta nombre");
            return;
        }if(txtaSinopsis.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Falta sinopsis");
            return;
        }
        // guarda una coleccion en bd
                try {
            Statement stm = Conexion.getConexion().createStatement();
            String consulta = "insert into colecciones values(id,'" + 
                    txtNombre.getText().trim() + "','"+ 
                    txtaSinopsis.getText().trim()+"')";
            System.out.println(""+consulta);
            stm.executeUpdate(consulta);
            //limpiamos los campos del formulario
            limpiar();
            //rellenamos todos los cmb para actualizar datos
            AltaComic.rellenarColecciones();
            BajaColeccion.rellenarColecciones();
            BajaComic.rellenarComics();
            ModificacionColeccion.rellenarColecciones();
            ModificacionComic.rellenarColecciones();
            ModificacionComic.rellenarComics();
            InformesComics.rellenarComics();
            InformesColecciones.rellenarColecciones();
            JOptionPane.showMessageDialog(this, "Colección insertada "
                    + "correctamente");
        } catch (SQLException e) {
            System.out.println(""+e.getErrorCode());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnAceptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextArea txtaSinopsis;
    // End of variables declaration//GEN-END:variables

}
